### ISSUE TITLE
Add a way to divide or subtract two Rainbows.

### ISSUE THREAD

**Issue by madisontbrady** [zkbt/chromatic#12]

**Comment by zkbt** [comment]
@madisontbrady , I'm delighted you're working on this. One thought that occurred to me is that we should require and strictly check that two 🌈 have identical wavelength and time arrays before doing any +-*/ with their flux values.

**Comment by madisontbrady** [comment]
It's a quick fix, I can make the adjustment.

**Comment by zkbt** [comment]
Closed by #14 .

You can now +-*/ with...
            1) float
            2) 1D array with same length as wavelength axis
            3) 1D array with same length as time axis
            4) 2D array with same shape as rainbow flux
            5) Rainbow object with same dimensions (and exact wavelength + time values) as self
