### ISSUE TITLE
Time axis not identified for NIRSpec ERS data

### ISSUE THREAD

**Issue by catrionamurray** [zkbt/chromatic#144]
Downloaded the x1dints.fits file from:
https://stsci.app.box.com/s/f6ehe1i2tsn9dih8zl0emyvjm9vemh1r/folder/154981726767
and loaded it into a Rainbow. I got the following error:
`🌈 Warning: No times found! Making up imaginary ones!`

**Comment by catrionamurray** [comment]
Also when I normalized the data the errors didn't normalize?

**Comment by zkbt** [comment]
The lack of times is just because the simulated data simply didn't have times associated with them. The extension that was supposed to contain them was totally empty. I think somewhere on slack there was a text file and/or numpy save file containing a reasonable list of imaginary times for them. Hopefully this won't be a problem with the real data?!

**Comment by zkbt** [comment]
I'm not seeing the uncertainty normalization problem, but I did some fussing with the `uncertainty` math recently-ish, so there's a possibility that this got accidentally got fixed? Here's what I tried:
```python
from chromatic import *
r = read_rainbow('NIRSpec-x1dints/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_MOD_injected_x1dints.fits')
r.imshow_quantities(['flux', 'uncertainty'])
r.normalize().imshow_quantities(['flux', 'uncertainty'], vmin=0, vmax=2)
```
![image](https://user-images.githubusercontent.com/4691081/178314655-1a602db7-c2c3-4085-9b72-51ad4eff9db3.png)
![image](https://user-images.githubusercontent.com/4691081/178314677-b4cae46d-69d2-4a6a-8cd7-bae72b61b8b5.png)

which seems to show the uncertainties getting normalized out. Perhaps try again with a version >=0.2.9?

**Comment by zkbt** [comment]
I'm going to close this issue, choosing not to worry too much about the specifics of the simulated datasets. If someone finds this issue later on, trying to work with the ground-testing data with NIRSpec, please open a new Issue (or reopen this one), and we'll fix it!
