### ISSUE TITLE
Add a `Rainbow.plot()` of a per wavelength time series

### ISSUE THREAD

**Issue by mustaric** [zkbt/chromatic#16]
This plot should create 1 time series plot for each wavelength in the data with vertical offsets between them. For example, something like Figure 3 of https://ui.adsabs.harvard.edu/abs/2007ApJ...655..564K/abstract

**Comment by zkbt** [comment]
Closed by #17 by the amazing @mustaric ! 

We might want to tweak some of the ways that options get passed through and how exactly we organize the files, but it works great!
