### ISSUE TITLE
Add inflate_uncertainty action

### ISSUE THREAD

**Issue by Pat-Wachiraphan** [zkbt/chromatic#173]
It seems that uncertainty from the data might be underestimated for various reason. So, It would be good to have an action to inflate uncertainty to ~photon noise.

**Comment by catrionamurray** [comment]
I do this manually right now in chromatic_fitting!

**Comment by Pat-Wachiraphan** [comment]
> I do this manually right now in chromatic_fitting!

I requested the pull already, in the mean time if you want you can change the branch to add-inflate-uncertainty-action to use the action!
