### ISSUE TITLE
Add S4*Save.dat reader

### ISSUE THREAD

**Issue by catrionamurray** [zkbt/chromatic#175]
Currently chromatic cannot read the `Meta_Save.dat` files for Stage 4 (only 3)

**Comment by catrionamurray** [comment]
If I try to open it with the `eureka_s3_txt` option I get this error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
`

**Comment by zkbt** [comment]
Check with the eureka folks, but I *thought* that the `Meta_Save.dat` were just their qualitative description of what had happened up until that point of the processing. The quantitative time-series data is now all in *SpecData* or *LCData*. I tried loading a `Meta_Save.dat` about a week ago and convinced myself that the contents and size didn't seem to have time-series data I wanted. 

If there is essential information we want in there, I think we just need a nudge from them on how to load it. I suspect it might be a pickle embedded in a text file, or some other weird dump of info?

**Comment by zkbt** [comment]
@catrionamurray , can you please let me know whether this is still an issue we should worry about or we should close it?

**Comment by catrionamurray** [comment]
I don't think this is an issue any more, I think you're right about the Meta_Save.dat just being meta data and not the most useful output!

**Comment by catrionamurray** [comment]
It could be a useful enhancement for the future to be able to read this (in case there's other metadata we want to store in the Rainbows), but definitely not essential!

**Comment by zkbt** [comment]
OK, we'll close it for now, but I agree it'll be useful to keep an eye on how the Eureka! outputs evolve.
