### ISSUE TITLE
wscale issue in Rainbow class

### ISSUE THREAD

**Issue by madisontbrady** [zkbt/chromatic#2]
In rainbow.py:

The parameter wscale (which refers to whether the wavelength axis in the Rainbow class is linear, logarithmic, or neither) is not initialized when the object is created.  This can create problems if you try to plot a Rainbow object with imshow.

**Comment by zkbt** [comment]
While I'm solving this, I think I'm going to move `wscale` (and any other similar types of attributes we'll want to keep track of) into a dictionary (probably named `.metadata`). I think that'll make it easier to copy information along from one 🌈 to another.

**Comment by zkbt** [comment]
Closed by #15
