### ISSUE TITLE
rainbow imshow quirk 

### ISSUE THREAD

**Issue by madisontbrady** [zkbt/chromatic#3]
In rainbow.py (also carries on to simulated rainbows, as well):

Not really a bug, but I'm noting it here just in case someone else runs into this.

The fluxes (or whatever other fluxlike object) of a rainbow object are stored in an array with the shape (n_wl, n_time).  
However, it seems that, when plotting, the first row of the flux array corresponds to the maximum value in the wavelength array, instead of the minimum.  This is something that is important to keep in mind when supplying fluxes by hand to the rainbow class (it definitely tripped me up!).

**Comment by zkbt** [comment]
Ooh, that's a good catch. It would definitely be way more intuitive for the first row to be the lowest wavelength; we should set up that convention and make sure it propagates into imshow (probably with a `origin='lower'`) and wherever else is necessary.

**Comment by zkbt** [comment]
Yes, it looks like this was just a dumb flip that I had in the definition of `extent` in the imshow. I think I've fixed that now, but please keep an eye out for weird behavior like this!
