### ISSUE TITLE
Check which readers work and don't. 

### ISSUE THREAD

**Issue by zkbt** [zkbt/chromatic#42]
Go through the Data Challenge submissions for folder `C-time-series-extracted-1D-spectra`.
Figure out which extracted spectrum files can be loaded, and which can't.
Keep track in a google doc shared with Zach. 

Make sure you're starting from version 0.0.13.

@will-waalkes , could you help with this?

**Comment by will-waalkes** [comment]
Yes! I'll send you a google doc by tomorrow morning

**Comment by zkbt** [comment]
With @will-waalkes 's help, we got through all the files that were submitted by the (start of the) spring ers-transit data challenge. This [gist](https://gist.github.com/zkbt/ec890817811750e9a85cfd1a6cb84e23) shows how each of them can be read.

The necessary new readers were tidied up and documented in #56 .
