### ISSUE TITLE
Add a function to plot all `timelike` quantities.

### ISSUE THREAD

**Issue by zkbt** [zkbt/chromatic#47]
Many datasets will have multiple arrays associate with them that are "time-like", in the sense that there's one number for each time point. The most obvious time-like quantity is `time` itself, but there could be many others (average centroid shifts, detector temperatures, etc..). This is effectively trying to plot every array in the `rainbow.timelike` dictionary.

It'd be great to have a function that just makes a quick plot of all these quantities, in its own subplot. They should have a shared x-axis, so we can see things line up across all the panels. This might look something like `def plot_timelike_quantities(rainbow, quantities=None):`, where `quantities = None` would mean to just plot everything and `quantities = ['time', 'centroid', 'temperature']` would plot just a subset of quantities. 

To start developing this, the simplest approach is probably to just write a function in a notebook. Test it on some Rainbow object, and then once it behaves how you like, we can drop it into the code for the `chromatic` package. (I can post more specific instructions on how to do that below.) 

So, to get started, you might open a notebook and run  

```
from chromatic import *
rainbow = SimulatedRainbow().inject_transit()

def ...
```

and then start drafting your function.

**Comment by lcmayor** [comment]
Do you envision the x-axis being time, which makes the time vs time plot silly, or just an index?

**Comment by zkbt** [comment]
I think we're going to merge this with #48 , as discussed there.

**Comment by zkbt** [comment]
> Do you envision the x-axis being time, which makes the time vs time plot silly, or just an index?

I could see both being useful. An index would compress over gaps and make everything feel kind of uniformly important, while actual time or wavelength could be helpful for saying things like "that centroid wobble at the times right before transit" or "that bump in the uncertainties at 2.5 microns". 

Could we add a flag that could be like `x='index'` or `x='time'` or `x='wavelength`' (or, I guess, any other timelike or wavelike quantity) to decide whether to use an index or the actual quantity as the x-axis? To avoid the "time vs time" plot, we could check and remove the x quantity from the list of things to appear on the y axis.

**Comment by zkbt** [comment]
And if we merge the two functions, then I think `x='index'` should probably be the default, because it'd be the only one that would play nicely with both timelike and wavelike quantities.

**Comment by zkbt** [comment]
Thank you 🤩!
