### ISSUE TITLE
Object with name 'DN' already exists in namespace.

### ISSUE THREAD

**Issue by taylorbell57** [zkbt/chromatic#50]
Trying to import chromatic after installing it (either via pip or from GitHub with `pip install -e '.[develop]'`, I get the following error message. I'm using Python 3.9.7, astropy 4.3.1

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Input In [1], in <module>
> ----> 1 from chromatic import *
> 
> File ~/Downloads/chromatic/chromatic/__init__.py:2, in <module>
>       1 from .version import *
> ----> 2 from .rainbows import *
>       3 from .imports import *
>       4 from .resampling import *
> 
> File ~/Downloads/chromatic/chromatic/rainbows/__init__.py:1, in <module>
> ----> 1 from .rainbow import *
>       2 from .simulated import *
>       3 from .multi import *
> 
> File ~/Downloads/chromatic/chromatic/rainbows/rainbow.py:1, in <module>
> ----> 1 from ..imports import *
>       2 from ..talker import Talker
>       3 from .readers import *
> 
> File ~/Downloads/chromatic/chromatic/imports.py:37, in <module>
>      34 # For modelling transits.
>      35 import batman
> ---> 37 from .units import *
>      39 # define a driectory where we can put any necessary data files
>      40 data_directory = pkg_resources.resource_filename("chromatic", "data")
> 
> File ~/Downloads/chromatic/chromatic/units.py:12, in <module>
>       9 data_number_per_second = u.def_unit("DN/s")
>      10 data_number_per_second_sq = u.def_unit("(DN/s)^2")
> ---> 12 u.add_enabled_units([data_number, data_number_per_second, data_number_per_second_sq])
> 
> File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/astropy/units/core.py:448, in add_enabled_units(units)
>     446 context = _UnitContext(get_current_unit_registry())
>     447 # in this new current registry, enable the further units requested
> --> 448 get_current_unit_registry().add_enabled_units(units)
>     449 return context
> 
> File ~/miniconda3/envs/eureka/lib/python3.9/site-packages/astropy/units/core.py:203, in _UnitRegistry.add_enabled_units(self, units)
>     201 for st in unit._names:
>     202     if (st in self._registry and unit != self._registry[st]):
> --> 203         raise ValueError(
>     204             "Object with name {!r} already exists in namespace. "
>     205             "Filter the set of units to avoid name clashes before "
>     206             "enabling them.".format(st))
>     208 for st in unit._names:
>     209     self._registry[st] = unit
> 
> ValueError: Object with name 'DN' already exists in namespace. Filter the set of units to avoid name clashes before enabling them.
>

**Comment by zkbt** [comment]
Ah, interesting. That was a thing I had to add to try to read a file (maybe even your?!), but it's not surprising to me that one someone else's machine, maybe with a slightly different version of `astropy`, there might be a conflict. I'll switch that to a `try`, to handle corner cases.

**Comment by zkbt** [comment]
OK, @taylorbell57 , I think this should be fixed now in version `0.0.16`? I also fixed a bug in the eureka S3 reader, so I think it should now be able to read your extracted spectra. (At least, I was able to read of your submitted files with just `r = Rainbow(...)`. See #52 .

**Comment by zkbt** [comment]
Especially since your error didn't pop up on my own machine, can you please confirm my fix actually works before I close this out? I merged it into the main branch, so you should have it if you pull down the most recent development version.

**Comment by taylorbell57** [comment]
Can confirm that the issue is now resolved as of 0.0.16!
