### ISSUE TITLE
Add ability to inject a simulated transit into a `SimulatedRainbow`.

### ISSUE THREAD

**Issue by zkbt** [zkbt/chromatic#6]
It'd be great to be able to inject a fake transit signal into a simulated rainbow object. One structure I might imagine for this is a `SimulatedRainbow.inject_transit()` function that could take as inputs some transit parameters and inject a transit. (It'd be super snazzy if it could take arrays of  planet radii and limb-darkening coefficients, so we inject realistic transmission spectra!)

**Comment by madisontbrady** [comment]
I'm looking into this!  I currently have a decent amount done but need to clean up the interface.

**Comment by zkbt** [comment]
Awesome! I put this one up here for you! I'll assign you, and call it in-progress on the Project board!
