### ISSUE TITLE
Add function to convert rainbow to pandas dataframe

### ISSUE THREAD

**Issue by catrionamurray** [zkbt/chromatic#66]
Have an option to output rainbow object to pandas dataframe

**Comment by zkbt** [comment]
(No rush on this, I'm just going through and planning some next steps while I have a spare moment.)

I think you have this entirely written. I think the place to put it would be to create a new file that's something like `chromatic/rainbows/actions/pandas.py`, and put your function in there. Once you've written it there, you'll also need to import it into `chromatic/rainbows/actions/__init__.py` and directly into the `Rainbow` class definition, as happens down at the bottom of `chromatic/rainbows/rainbow.py`. 

Thanks!
