### ISSUE TITLE
Add support for `Astraeus` reader/writers.

### ISSUE THREAD

**Issue by zkbt** [zkbt/chromatic#75]
@kevin218 has written [Astraeus](https://github.com/kevin218/Astraeus) as a general framework for input/output of spectroscopic light curves (among other types of data) and incorporating it into [Eureka!](https://github.com/kevin218/Eureka). We should add a reader/writer pair that connects. 

One initial step would be for @kevin218 to please provide an example data product file that we could work with. Then, I think we can sketch out a reader and a writer that follow the normal `template.py` format.

**Comment by kevin218** [comment]
Have you looked at the Usage section from the [documentation]( https://kevin218.github.io/Astraeus/)? Similarly, the Tests directory generates small Xarray datasets that you can practice with.

If you're looking for something more realistic, I can send you actual Eureka savefiles. That probably won't happen until next week though.

**Comment by zkbt** [comment]
Hi @kevin218 , again in a "no rush because I can't get to it for a while" mode, sending an example eureka file would be the best, please! The easiest way to implement a `chromatic` reader is from a real file that contains at least times, wavelengths, fluxes, and uncertainties, along with any other diagnostic parameters you have (with whatever shapes).

**Comment by kevin218** [comment]
Here are Eureka! save files for Stages 3 and 4 containing the time-series of 1D spectra and the binned light curves.  I also have Stage 3 outputs with 2D fluxes, subtracted backgrounds, etc, but each file is several hundred MB.  If those data are also useful, then I can create a smaller version.
[Uploading S3+S4-NIRCam-W39.zip…]()

**Comment by kevin218** [comment]
J/K, the ZIP file isn't working for some reason.  I'll email it to you instead.
