### ISSUE TITLE
Add a `.flag_outliers` method.

### ISSUE THREAD

**Issue by zkbt** [zkbt/chromatic#98]
It'd be nice to have a quick way to flag individual time-series outliers. It should be an action that returns a copy of the existing `Rainbow` but with the `ok` array modified to reflect which points are outliers. It'd be good if it were robust to the presence of slowly-varying signals (like a well-sampled transit), so outliers could probably identified with some kind of sigma-clipping in the `np.diff` of each wavelength's light curve. 

This might commonly be called before binning, to remove bad points from bins. Let's be careful the uncertainties get handled well.

**Comment by kortizceballos** [comment]
Taking a crack at this one!

**Comment by kortizceballos** [comment]
Added a simple flag_outliers feature in #166. Worked pretty great without needing to remove astrophysical signals first. The action only modifies the rainbow's 'ok' array, it does not mess with anything else in the rainbow/data.

**Comment by zkbt** [comment]
I made a few tiny changes in #189 , including adding a `inject_outliers` to make it easier to test this.
